language: node_js

node_js:
  - "6"
  - "7"

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test -- --coverage
  - npm run build
  - npm run check:examples

after_success:
  - bash <(curl -s https://codecov.io/bash)
