language: node_js

node_js:
  - "6"
  - "7"

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.npm
  - examples/todo/node_modules

script:
  - npm run lint
  - npm run test -- --coverage
  - npm run build
  - npm run check:examples

after_success:
  - bash <(curl -s https://codecov.io/bash)
